version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  pull-request-branch-name:
    # Separate sections of the branch name with a hyphen
    # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
    separator: "-"
  open-pull-requests-limit: 10
